# -*- coding: utf-8 -*-
"""Gene Expression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/169wWG3GOplORMymxHZ2JN5Bm0kb2c4mL
"""

!pip install pandas
!pip install biopython

!pip install matplotlib

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# from IPython.utils.text import py3compat
# import streamlit as st
# import pandas as pd
# from io import StringIO
# from pyngrok import ngrok
# from Bio import SeqIO
# import matplotlib.pyplot as plt
# st.title("GENE EXPRESSION")
# st.header("MINI-DASHBOARD")
# 
# st.markdown("Upload a gene expression CSV file or paste a FASTA sequence")
# uploaded_file = st.file_uploader("Upload Gene Expression CSV", type=["csv"])
# 
# if uploaded_file is not None:
#   df = pd.read_csv(uploaded_file)
#   st.subheader("Gene Expression Data")
#   st.write(df)
#   st.dataframe(df)
# 
#   if "Gene" in df.columns and "Expression" in df.columns:
#     st.write("Gene Expression Plot")
#     fig.ax = plt.subplots()
#     ax.bar(df["Gene"], df["Expression"])
#     ax.set_xlabel("Gene")
#     ax.set_ylabel("Expression Level")
#     ax.set_title("Gene Expression Levels")
#     st.pyplot(fig)
#     else:
#     st.warning("Gene and Expression columns not found in the uploaded file.")
# 
#     st.write("---")
#     st.write("### Analyse FASTA Sequence")
# 
#     fasta_input = st.text_area("Enter a FASTA sequence", height=200)
# if fasta_input:
#   fasta_io = StringIO(fasta_input)
#   sequences = list(SeqIO.parse(fasta_io, "fasta"))
#   for record in SeqIO.parse(fasta_io, "fasta"):
#     st.write(f"Sequence ID: {record.id}")
#     st.write(f"Sequence Name: {record.name}")
#     st.write(f"Sequence Length: {len(record.seq)}")
#     st.write(f"GC Content: {round((record.seq.count('G') + record.seq.count('C'))/ len(record.seq) * 100, 2)}%")

